### ISSUE TITLE
Multiple Sass Files Out of Sync with Upstream Wagtail 1.10

### ISSUE THREAD

**Issue by jeffreyckchau** [alexgleason/wagtailatomicadmin#4]
![image](https://cloud.githubusercontent.com/assets/3045891/25763967/84140a58-319a-11e7-9840-316bd02bbb06.png)

Hello,

As shown in the attached screenshot, upgrading to Wagtail 1.10 with wagtailatomicadmin installed causes an issue with the breadcrumb. I realize this is due to the forked wagtailadmin .scss files being out of date with the updated source files in upstream Wagtail, so I wonder what else could have changed that I have not yet found. 

I'd be happy to submit a PR to fix this, but I think it might be a better idea for the maintainers with more knowledge of the differences between wagtailatomicadmin and standard wagtailadmin's styling to make the change.

Please advise.

**Comment by alexgleason** [comment]
Hey @jeffreyckchau, thanks for raising this!

The project needs new maintainers. Unfortunately I haven't had the chance to touch Wagtail in some time. Updating this may be difficult. I wish I could just pull the latest changes and merge with mine, but wagtailadmin is a subdirectory in the main repo, so it doesn't have commits on its own.

In retrospect, I probably should have used git-subtree to pull out the relevant commits, then written a script to make a subtree of the latest version to merge changes. This will likely be the best approach for the long-term and I would suggest trying this if you seriously want to improve the project.

You could probably figure out where the original was taken from by looking at the dates in the commit log. I do remember that I copied the sass from the latest stable version at the time. I want to say it was around like 1.7.

Finally, the easier but more short-sighted option would be to just write new CSS that will fix the errors. I'm willing to go whatever direction the community wants. In the meantime we should probably at least change the package so it rejects install on Wagtail >= 1.10.

**Comment by alexgleason** [comment]
Actually another option would be to just convince the Wagtail maintainers to merge these changes. I haven't tried.

**Comment by jeffreyckchau** [comment]
Hi @alexgleason, I think in the short term, I'm okay with just pulling in the upstream changes into the repository and hard committing them. 

However, I do want to pursue your solution in the long term. I've never worked with git submodules myself, but I'll happily do some investigation and see about setting up the pipeline you described.

In the meantime, I will submit a PR with the upstream styling changes integrated which hopefully doesn't break :P

**Comment by alexgleason** [comment]
Great, thanks!

**Comment by jeffreyckchau** [comment]
Hi @alexgleason, sorry for the delay. I've submitted the PR. If you or any other maintainers could take a look, that would be extremely helpful!

**Comment by jeffreyckchau** [comment]
Merged in #5 .
